# /etc/powerdns/pdns.conf — dns21 (maquette PAR2) — Lucas
launch=gsqlite3
gsqlite3-database=/tmp/pdns.sqlite3
gsqlite3-dnssec=yes

# écoute
local-address=0.0.0.0
local-port=53

# zone primaire, notifie le futur secondaire
primary=yes
allow-axfr-ips=0.0.0.0/0
also-notify=10.20.20.11

# mises à jour dynamiques pour le DHCP de PAR2 et la CI
dnsupdate=yes
allow-dnsupdate-from=10.10.0.0/16,10.20.0.0/16

# API pour la CI
api=yes
api-key=Lucas-PAR2-cle-api-2026-maquette
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0

# valeurs par défaut
default-ttl=60
default-soa-content=dns21.par2.medisphere.internal hostmaster.@ 0 60 60 60 60

# debug
loglevel=9
log-dns-queries=yes
