---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Préparer un nœud OpenStack pour Kolla-Ansible (interfaces stables, MTU, KVM, temps)
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
