---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Autorités de certification du lab dans le magasin système (Debian)
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
