---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: VIP keepalived de l'API et certificat valable pour le nom du cluster Proxmox VE hv-par1
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
