---
# molecule/step_ca/converge.yml — applique le rôle step_ca avec la PKI de test (prepare.yml).
- name: Converge — rôle step_ca
  hosts: molecule
  become: true
  vars:
    pki: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/pki-test"
    step_ca_noms_dns:
      - ca.molecule.test
      - "{{ ansible_facts['default_ipv4']['address'] }}"
    step_ca_racine_crt: "{{ pki }}/root_ca.crt"
    step_ca_intermediaire_crt: "{{ pki }}/intermediate_ca.crt"
    step_ca_mot_de_passe: molecule-inter-mot-de-passe-de-test
    step_ca_provisioners:
      - type: JWK
        name: admin
        key: "{{ lookup('ansible.builtin.file', pki ~ '/admin.pub.json') | from_json }}"
        encryptedKey: "{{ lookup('ansible.builtin.file', pki ~ '/admin.enc') }}"
        claims:
          maxTLSCertDuration: 2160h
          defaultTLSCertDuration: 720h
          enableSSHCA: true
      - type: ACME
        name: acme
        claims:
          maxTLSCertDuration: 720h
          defaultTLSCertDuration: 720h
      - type: SSHPOP
        name: sshpop
        claims:
          enableSSHCA: true
  roles:
    - role: step_ca
