---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Planifie les sauvegardes Mariabackup de Kolla-Ansible depuis l'hôte de déploiement
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
