---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Serveur DHCPv4 Kea 3.0 pour des sous-réseaux relayés (API de contrôle, DDNS)
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
