---
# host_vars/spine02/frr.yml — état de fin de M07-E06 : OSPF zone 0.
frr_interfaces:
  - nom: lo
    adresses: [10.10.255.2/32]
    ospf: {zone: 0.0.0.0}
  - nom: eth1
    description: vers leaf01 (vfab3)
    ospf: {zone: 0.0.0.0, reseau: point-to-point, cout: 10, passive: false}
  - nom: eth2
    description: vers leaf02 (vfab4)
    ospf: {zone: 0.0.0.0, reseau: point-to-point, cout: 10, passive: false}

frr_ospf:
  router_id: 10.10.255.2
