---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Sauvegarde hors cluster de Ceph (exports RBD incrémentaux et configuration) vers PBS
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
