---
- name: installer fail2ban
  apt: name=fail2ban state=latest update_cache=yes
  when: ansible_distribution == "Debian"

- name: config
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  when: "{{ fail2ban_actif }}"
  notify: restart fail2ban

- name: recharger fail2ban
  command: fail2ban-client reload
  when: fail2ban_jails

- name: service
  service: name=fail2ban state=started enabled=yes
