---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Résolveur PowerDNS Recursor 5.4 (YAML), zones internes relayées, validation DNSSEC
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
