# shellcheck shell=bash
# shellcheck disable=SC2016  # commandes passées entre apostrophes à bash -c, évaluées plus tard
#
# check-E15.sh — M01-E15 : pre-commit dans plateforme/medisphere
# Lancé depuis adm01. Lecture seule (outils locaux, clone $WB_DEPOT, API GitLab).

title "M01-E15 — pre-commit : des contrôles versionnés avec le dépôt"
require_cmd curl jq git

_m01_depot="${WB_DEPOT:-$HOME/medisphere}"

check_output "pre-commit 4.x disponible dans le PATH" '^pre-commit 4\.' pre-commit --version

_m01_cfg="$(gitlab_api "projects/plateforme%2Fmedisphere/repository/files/.pre-commit-config.yaml/raw?ref=main" 2>/dev/null)" || _m01_cfg=""
check_cmd ".pre-commit-config.yaml est sur main de plateforme/medisphere" test -n "$_m01_cfg"
for _m01_h in trailing-whitespace end-of-file-fixer check-yaml check-added-large-files \
              check-merge-conflict detect-private-key gitleaks commitlint; do
  check_cmd "hook « $_m01_h » déclaré" grep -Eq "id:[[:space:]]*$_m01_h([[:space:]]|$)" <<<"$_m01_cfg"
done
check_cmd "les hooks commit-msg sont installés par défaut (default_install_hook_types)" \
  grep -Eq '^default_install_hook_types:.*commit-msg' <<<"$_m01_cfg"
_m01_revs_epingles() {
  grep -Eq '^[[:space:]]*rev:' <<<"$1" || return 1
  ! grep -Eiq '^[[:space:]]*rev:[[:space:]]*["'"'"']?(main|master|head|latest)["'"'"']?[[:space:]]*(#.*)?$' <<<"$1"
}
check_cmd "chaque dépôt de hooks est épinglé (rev: étiquette ou empreinte, jamais une branche)" \
  _m01_revs_epingles "$_m01_cfg"

check_cmd "dans $_m01_depot, la configuration est valide (pre-commit validate-config)" \
  bash -c 'cd "$1" && pre-commit validate-config .pre-commit-config.yaml' _ "$_m01_depot"
check_cmd "dans $_m01_depot, le hook pre-commit est installé par pre-commit" \
  grep -q 'File generated by pre-commit' "$_m01_depot/.git/hooks/pre-commit"
check_cmd "dans $_m01_depot, le hook commit-msg est installé par pre-commit" \
  grep -q 'File generated by pre-commit' "$_m01_depot/.git/hooks/commit-msg"

# État de main (dernier fetch) : les correctifs automatiques ont été appliqués
_m01_espaces() {
  git -C "$_m01_depot" rev-parse -q --verify origin/main >/dev/null || return 1
  ! git -C "$_m01_depot" grep -I -l -E '[[:blank:]]+$' origin/main -- . ':(exclude)*.md' >/dev/null 2>&1
}
check_cmd "main ne contient plus d'espaces en fin de ligne (hors Markdown)" _m01_espaces
_m01_gros() {
  git -C "$_m01_depot" rev-parse -q --verify origin/main >/dev/null || return 1
  ! git -C "$_m01_depot" ls-tree -r -l origin/main 2>/dev/null | awk '$4 > 512000 {found=1} END {exit !found}'
}
check_cmd "main ne contient aucun fichier de plus de 500 Ko" _m01_gros
