---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Autorité de certification en ligne step-ca (intermédiaire d'une racine hors ligne, ACME, CA SSH)
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
