! frr.conf — rt-bord-01 (InfoGér), export pour MédiSphère
frr version 8.4
frr defaults traditional
hostname rt-bord-01
log syslog debugging
debug bgp updates
debug bgp neighbor-events
service integrated-vtysh-config
!
ip route 10.10.0.0/16 blackhole
!
ip prefix-list CLIENTS seq 10 permit 10.0.0.0/8 le 32
ip prefix-list AGENCE seq 10 permit 10.30.0.0/16 le 32
!
route-map AGENCE-IN permit 10
 match ip address prefix-list AGENCE
exit
!
router bgp 65000
 no bgp ebgp-requires-policy
 timers bgp 1 3
 neighbor 192.0.2.1 remote-as 64600
 neighbor 192.0.2.1 description transit NetCo
 neighbor 192.0.2.1 password InfoGer2019
 neighbor 10.255.2.2 remote-as 65030
 neighbor 10.255.2.2 description agence Lyon
 neighbor 10.255.2.2 password InfoGer2019
 neighbor 10.255.2.2 ebgp-multihop 255
 neighbor CLIENTS peer-group
 neighbor CLIENTS remote-as external
 neighbor CLIENTS password InfoGer2019
 bgp listen range 10.10.0.0/16 peer-group CLIENTS
 !
 address-family ipv4 unicast
  network 10.10.0.0/16
  redistribute connected
  redistribute static
  neighbor 10.255.2.2 route-map AGENCE-IN in
  neighbor 10.255.2.2 allowas-in
  neighbor CLIENTS prefix-list CLIENTS in
 exit-address-family
exit
!
end
