---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Serveur DNS faisant autorité PowerDNS 5.0 (gsqlite3, API), zones générées ou pilotées par API
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
