---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Configuration de l'hôte git01 autour de GitLab CE (sans gérer GitLab lui-même)
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
