---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Laboratoire de bonding (active-backup, 802.3ad) entre deux espaces de noms (maquette M07)
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
