---
galaxy_info:
  author: Équipe Plateforme MédiSphère
  description: Page d'information interne (nginx, HTTPS, certificat ACME de ca01) — M06-E34
  license: proprietary
  min_ansible_version: "2.19"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
